version: "3"
services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: curotec_app
        restart: unless-stopped
        volumes:
            - ./:/var/www/html
        depends_on:
            - db
        networks:
            - curotec

    nginx:
        image: nginx:alpine
        container_name: laravel_nginx
        restart: unless-stopped
        ports:
            - "8000:80"
        volumes:
            - ./:/var/www/html
            - ./.docker/nginx:/etc/nginx/conf.d/
        depends_on:
            - app
        networks:
            - curotec

    db:
        image: postgres:15
        container_name: laravel_db
        restart: unless-stopped
        environment:
            POSTGRES_DB: laravel
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: secret
        volumes:
            - pgdata:/var/lib/postgresql/data
        ports:
            - "5432:5432"
        networks:
            - curotec

networks:
    curotec:
        driver: bridge

volumes:
    pgdata:
        driver: local
